### ISSUE TITLE
Installed in Xcode but does not do open the popup

### ISSUE THREAD

**Issue by ForestRingGames** [markohlebar/Import#13]
I've got it installed in Xcode Version 8.0 (8A218a) and Mac OS 10.12 (16A323) and it shows under Editor -> Import. If I press the hot key or click on it via them menu, nothing at all happens.

When pressing the hotkey the top bar flashes....so it definitely triggers the "Import Extension", but the Import extension does not do a thing. 

How to fix this?

**Comment by markohlebar** [comment]
Hi @ForestRingGames there is no popup in Import. You have to start typing what you want to import and use Xcode's own autocomplete feature to write the import string (that is the popup you see in the video). This is due to the limitations of the XcodeEditor API, you can't show any third party extension UI in the editor.
Can you please consult the [Usage section](https://github.com/markohlebar/Import/blob/master/README.md#usage), and if that is not clear, please tell me what I can add to make it clearer?

**Comment by ForestRingGames** [comment]
Argh! So I just type my include statement anywhere, press the hotkey and it moves it up. 

Sorry, I didn't understand that.

Actually, this is very awesome! Peckham didn't support C++ properly (at least It never worked for me, you might remember some of my issues that I reported ;) ). But this thing does work perfectly. Thanks!

**Comment by markohlebar** [comment]
@ForestRingGames ah yeah sorry for the confusion :) yeah I remember you raising an issue about that, thanks for using both Peckham and Import 👍

**Comment by ForestRingGames** [comment]
Quite Ironic how the drastic removal of plugins made my UX better haha, keep up the good work! ;)

**Comment by markohlebar** [comment]
That was my thoughts as well when I built it, this works out of the box with any language, and much less code :) Cheers!
